providers = ["java"]

[phases.setup]
# install JDK 21 for the build
nixPkgs = ["jdk21"]

[phases.build]
cmds = ["./mvnw -DskipTests package"]

[start]
cmd = "java -jar target/backend-0.0.1-SNAPSHOT.jar"
